name = "SDPAFamily"
uuid = "bfe18334-aefd-11e9-1109-4bf2b15a5b91"
authors = ["Eric P. Hanson and Jiazheng Zhu"]
version = "0.1.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SDPA_jll = "7fc90fd6-dbef-5a6a-93f8-169f2a2e705b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BinaryProvider = "0.5"
DoubleFloats = "0.9.9"
MathOptInterface = "0.9.5"
julia = "1.5"

[extras]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg", "GenericLinearAlgebra", "Random", "Statistics", "DoubleFloats", "Convex"]
