name = "SDPA_GMP"
uuid = "bfe18334-aefd-11e9-1109-4bf2b15a5b91"
authors = ["Eric P. Hanson and Jiazheng Zhu"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MathOptInterface = "~0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
